# Generated by Django 3.2 on 2022-07-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220729_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.address')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('common.address',),
        ),
    ]
